# Generated by Django 5.2.4 on 2025-07-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('empleado', models.BooleanField(default=False)),
            ],
        ),
    ]
