# Generated by Django 5.2.4 on 2025-07-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('talle', models.CharField(max_length=10)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
